language: node_js
node_js:
  - "8"
sudo: required  
addons:
  chrome: stable  
  sauce_connect: true
before_script:
  - npm install -g codecov
script:
  - npm run ci
after_script:
  - codecov --disable=gcov 
